### ISSUE TITLE
The github deploy does not publish the User- / Developer manual

### ISSUE THREAD

**Issue by franzTobiasDLR** [virtualsatellite/ci-actions#2]
Releases with the ci-actions do not publish the documentations on github.

**Comment by PhilMFischer** [comment]
Well, it does for Core. Is this an issue specific to one of the virtual satellite versions?

**Comment by franzTobiasDLR** [comment]
I think this is an old issue which if've fixed in one of the last releases but forgot to close the ticket. At some point the actions didn't deploy the manual in core.
